#!/bin/sh
echo ""
echo "Initializing ${formic.action}er ..."
echo ""

# create a temp directory to extract to.
WRKDIR=`mktemp -d /tmp/formic_XXXXXX`

# determine start of archive
START=`awk '/^__BEGIN_ARCHIVE__/ { print NR + 1; exit 0; }' $0`

# Take the archive portion of this file and extract it.
tail -n +$START $0 | gzip -dc | tar x -C $WRKDIR

# execute the install script
PREV=`pwd`
cd $WRKDIR

if [ -z "$DISPLAY" ] ; then
  ./formic ${formic.action} -Dformic.console=true $@
else
  ./formic ${formic.action} $@
fi

# delete the temp files
cd $PREV
rm -rf $WRKDIR

exit 0

__BEGIN_ARCHIVE__
