#!/bin/sh

# Formic installer framework.
# Copyright (C) 2004 - 2006  Eric Van Dewoestine
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# Author: Eric Van Dewoestine

# Script used to extract installer and bootstrap installation.

echo ""
echo "Initializing ${formic.action} ..."
echo ""

# create a temp directory to extract to.
WRKDIR=`mktemp -d /tmp/formic_XXXXXX`

# determine start of archive
START=`awk '/^__BEGIN_ARCHIVE__/ { print NR + 1; exit 0; }' $0`

# Take the archive portion of this file and extract it.
tail -n +$START $0 | gzip -dc | tar x -C $WRKDIR

# execute the install script
PREV=`pwd`
cd $WRKDIR

if [ -z "$DISPLAY" ] ; then
  ./formic ${formic.action} -Dformic.console=true $@
else
  ./formic ${formic.action} $@
fi

EXIT_CODE=$?

# delete the temp files
cd $PREV
rm -rf $WRKDIR

if [ $EXIT_CODE -gt 0 ]; then
  echo "Installer failed.  See /tmp/install.log for details."
fi
exit $EXIT_CODE

__BEGIN_ARCHIVE__
