#!/bin/sh

# Formic installer framework.
# Copyright (C) 2004 - 2006  Eric Van Dewoestine
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

# Author: Eric Van Dewoestine

CUR_PATH=`dirname $0`

export LD_LIBRARY_PATH="$CUR_PATH/../lib/native/linux/"

$CUR_PATH/ant -f $CUR_PATH/../../../src/samples/install.xml -lib $CUR_PATH/../../../src/samples $*
